# Generated by Django 5.2.6 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0006_mission_banner_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
