# Generated by Django 5.2.6 on 2026-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0007_mission_client_id_missionjiaparticipant_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="payment_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mpesa_now", "M-Pesa now"),
                    ("pay_later", "Pay later"),
                    ("on_arrival", "On arrival"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
