# Generated by Django 5.2.6 on 2026-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0008_missionjiaparticipant_payment_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="consent_code_of_conduct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="consent_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("sponsored", "Sponsored"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="missionjiaparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("waitlist", "Waitlist"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
