# Generated by Django 5.2.6 on 2026-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0009_missionjiaparticipant_consent_code_of_conduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="souls_reached",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Reported crowd figure for everyone talked to, broader than souls won",
                null=True,
            ),
        ),
    ]
