# Generated by Django 5.2.6 on 2026-08-29 20:54

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "client_mutation_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("entity", models.CharField(max_length=30)),
                ("op", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("result_id", models.IntegerField(blank=True, null=True)),
                (
                    "result_client_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_mutations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sync_mutations",
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
