# Generated by Django 5.2.6 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0002_alter_soul_location_alter_soul_mission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressupdate",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="soul",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
