# Generated by Django 5.2.6 on 2026-08-29 21:23

from django.db import migrations, models


STATUS_MAP = {
    "new_convert": "new_believer",
    "active": "growing",
    "follow_up": "growing",
}


def migrate_status_values(apps, schema_editor):
    Soul = apps.get_model("souls", "Soul")
    for old_value, new_value in STATUS_MAP.items():
        Soul.objects.filter(status=old_value).update(status=new_value)


def reverse_status_values(apps, schema_editor):
    Soul = apps.get_model("souls", "Soul")
    Soul.objects.filter(status="new_believer").update(status="new_convert")
    Soul.objects.filter(status="growing").update(status="follow_up")


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0003_progressupdate_client_id_soul_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="contact_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("born_again", "Born again"),
                    ("already_believer", "Already believer"),
                    ("not_yet", "Not yet"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="soul",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_yet_saved", "Not yet saved"),
                    ("new_believer", "New believer"),
                    ("growing", "Growing"),
                    ("rooted", "Rooted"),
                    ("in_a_church", "In a church"),
                ],
                default="new_believer",
                max_length=50,
            ),
        ),
        migrations.RunPython(migrate_status_values, reverse_status_values),
    ]
