# Generated by Django 5.2.6 on 2026-08-29 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0004_soul_contact_outcome_alter_soul_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progressupdate",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_progress_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="next_check_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reached", "Reached"),
                    ("no_answer", "No answer"),
                    ("rescheduled", "Rescheduled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressupdate",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("call", "Call"),
                    ("whatsapp", "WhatsApp"),
                    ("visit", "Visit"),
                    ("service", "Service"),
                    ("note", "Note"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="last_contacted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Derived from progress updates, never written directly",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="next_check_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
