# Generated by Django 5.2.6 on 2026-08-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_missions", "0001_initial"),
        ("souls", "0005_progressupdate_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="personal_mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="souls",
                to="personal_missions.personalmission",
            ),
        ),
    ]
