# Generated by Django 5.2.6 on 2026-08-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0006_soul_personal_mission"),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="consent_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="soul",
            name="consent_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soul",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tombstone, set when merged into another soul",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="do_not_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="soul",
            name="do_not_contact_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soul",
            name="possible_duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="possible_duplicates",
                to="souls.soul",
            ),
        ),
    ]
