# Generated by Django 5.2.6 on 2026-08-30 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("souls", "0007_soul_consent_given_soul_consent_recorded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="soul",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary volunteer responsible for follow-up",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_souls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="soul",
            name="church_connected",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="soul",
            name="co_carers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other volunteers with shared follow-up access to this soul",
                related_name="co_cared_souls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
