# Generated by Django 5.2.6 on 2026-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_bio_user_church_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Kenya DPA deletion request — data purge handled separately, not an immediate wipe",
                null=True,
            ),
        ),
    ]
