# Generated by Django 5.2.6 on 2026-08-29 21:50

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "client_id",
                    models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("one_time", "One time"), ("ongoing", "Ongoing")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "rhythm",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "rhythm_day",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="0-6, Monday-Sunday", null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("reminder_enabled", models.BooleanField(default=False)),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "what_happened",
                    models.TextField(
                        blank=True, help_text="One-time missions only", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personal_missions",
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
