# Generated by Django 5.2.6 on 2026-08-29 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalmission",
            name="rhythm_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0-6, Monday-Sunday",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
