# Generated by Django 5.2.6 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonies", "0002_miracle_is_selected_alter_testimony_is_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="miracle",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="testimony",
            name="client_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
