# Generated by Django 5.2.6 on 2026-08-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_missions", "0001_initial"),
        ("testimonies", "0003_miracle_client_id_testimony_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="miracle",
            name="is_personal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="miracle",
            name="personal_mission",
            field=models.ForeignKey(
                blank=True,
                help_text="The personal mission associated with this miracle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="miracles",
                to="personal_missions.personalmission",
            ),
        ),
        migrations.AddField(
            model_name="testimony",
            name="is_personal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimony",
            name="personal_mission",
            field=models.ForeignKey(
                blank=True,
                help_text="The personal mission associated with this testimony",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonies",
                to="personal_missions.personalmission",
            ),
        ),
    ]
