# Generated by Django 5.2.6 on 2026-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonies", "0004_miracle_is_personal_miracle_personal_mission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miracle",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miracle",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="miracle",
            name="third_party_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="miracle",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("anonymous", "Anonymous"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testimony",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimony",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testimony",
            name="third_party_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimony",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("anonymous", "Anonymous"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
