# Generated by Django 5.2.6 on 2026-08-30 09:59

import base.models
import django.db.models.deletion
import testimonies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0008_missionjiaparticipant_payment_timing"),
        ("personal_missions", "0002_alter_personalmission_rhythm_day"),
        ("souls", "0007_soul_consent_given_soul_consent_recorded_at_and_more"),
        ("testimonies", "0005_miracle_rejection_reason_miracle_review_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "client_id",
                    models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the highlight", max_length=255
                    ),
                ),
                ("content", models.TextField(help_text="Content of the highlight")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo associated with the highlight",
                        null=True,
                        upload_to=testimonies.models.get_highlights_dir,
                    ),
                ),
                ("is_personal", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("anonymous", "Anonymous"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("third_party_consent", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The mission associated with this highlight",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="missions.mission",
                    ),
                ),
                (
                    "personal_mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The personal mission associated with this highlight",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlights",
                        to="personal_missions.personalmission",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        blank=True,
                        help_text="The soul associated with this highlight",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="souls.soul",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who submitted the highlight",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Highlight",
                "verbose_name_plural": "Highlights",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
