# Generated by Django 5.2.6 on 2026-08-30 13:58

import base.models
import django.db.models.deletion
import testimonies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonies", "0006_highlight"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighlightPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to=testimonies.models.get_highlight_photo_dir
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="testimonies.highlight",
                    ),
                ),
            ],
            options={
                "db_table": "highlight_photos",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="MiraclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to=testimonies.models.get_miracle_photo_dir
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "miracle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="testimonies.miracle",
                    ),
                ),
            ],
            options={
                "db_table": "miracle_photos",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
        migrations.CreateModel(
            name="TestimonyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to=testimonies.models.get_testimony_photo_dir
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "testimony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="testimonies.testimony",
                    ),
                ),
            ],
            options={
                "db_table": "testimony_photos",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.models.ToDictMixin),
        ),
    ]
